
api:
  key: ${API_KEY:4P0xIsuOQIRoGEQBvs0ZJJyEuxpYi38G}
  url: ${API_URL:https://api.apilayer.com/exchangerates_data/convert}

server:
  port: '{cipher}2ff2a877b9c1f6c4dd1b315c2afdd4a2d1b4ace8c9d655cf0a73b339220bf6ce'

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USERNAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://localhost:5432/software}
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: currency-converter

keycloak:
  auth-server-url: http://localhost:9090
  autodetect-bearer-only: true
  credentials:
    secret: dH8SLOVQIus1f703zsbsRLBbGLY9crlk
  realm: software
  resource: backend
  ssl-required: external
  use-resource-role-mappings: false
  security-constraints:
    - auth-roles:
        - ADMIN
      security-collections:
        - name: SERVICIOS DEL ADMINISTRADOR
          methods:
            - GET
          patterns:
            - /api/currency/*
    - security-collections:
        - name: TEST NOTIFICACIONES
          methods:
            - GET
          patterns:
            - /api/currency/test-notification

management:
  endpoints:
    web:
      exposure:
        include: "*"


eureka:
  client:
    enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://ms-discovery:8761/eureka/
