server:
  port: 5050
  
spring:
  application:
    name: ms-customer
  rabbitmq:
    host: sparrow-01.rmq.cloudamqp.com
    port: 5672
    username: goejopzh
    password: 6jDIN535rF99TArhWUNOyCkB17rMfV6W
    virtual-host: goejopzh
  zipkin:
    enabled: false
    locator:
      discovery:
        enabled: false

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://ms-dicovery:8761/eureka/
    enabled: false
